# Use container-based infrastructure
sudo: false

language: scala

jdk: openjdk8

scala:
  - 2.13.0

env:
  - COURSIER_CACHE="sbt-cache/.coursier"

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $COURSIER_CACHE
    - $HOME/.sbt/boot/

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scapegoat testAndCoverageReport
after_success:
  - sbt coveralls

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
