 # Use container-based infrastructure
sudo: false

language: scala

jdk: oraclejdk8

scala:
  - 2.13.0-M1

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk: oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
